version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_gestion_budget
    environment:
      POSTGRES_DB: gestion_budget_esp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: api_gestion_budget
    ports:
      - "5000:5000"
    # depends_on:
    #   - postgres
    environment:
      DB_HOST: dpg-d1njb4bipnbc73anmn90-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_USER: gestion_budget_esp_user
      DB_PASSWORD: 3llUKuFKGlVSdy1gzs5q5BfptCbWPXAC
      DB_NAME: gestion_budget_esp
      JWT_SECRET: supersecret
      JWT_EXPIRATION: 2h
      MAIL_USER: espbudget@gmail.com
      MAIL_PASS: jktacretwqiiazmx
      MAIL_SERVICE: gmail
      FRONTEND_URL1: https://frontend-gestion-budget-esp.onrender.com
      FRONTEND_URL2: https://set-password-for-budget-esp.onrender.com
    volumes:
      - ./backend:/app
    command: sh -c "sleep 15 && npm run dev"

volumes:
  postgres_data: